// src/routes/sticker/[sid]/+page.svelte
<script lang="ts">
  import Icon from '@iconify/svelte'
  import { m, resolveMultilingual, localizedPath } from '$lib/i18n'
  import { locale } from '$lib/locale.svelte'
  import type { PageData } from './$types'

  interface Props {
    data: PageData
  }
  const { data }: Props = $props()

  const downloadImage = async (imagePath: string) => {
    const response = await fetch(imagePath)
    const blob = await response.blob()
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = imagePath.split('/').pop() ?? 'sticker.png'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }
</script>

<svelte:head>
  <title>{m().sticker.title} [{data.sid}]</title>
  <meta name="description" content={m().sticker.description} />
</svelte:head>

<div class="grid grid-cols-2 gap-5 sm:grid-cols-3 md:grid-cols-4">
  {#each data.stickers as sticker (sticker.pid)}
    <article
      class="relative flex flex-col gap-2 overflow-hidden border bg-content1 p-3 shadow-sm transition hover:border-primary hover:shadow-md"
    >
      <div class="aspect-square w-full overflow-hidden">
        <img
          src="/stickers/KUNgal{data.sid}/{sticker.pid}.webp"
          alt=""
          width="320"
          height="320"
          loading="lazy"
          class="h-full w-full object-cover"
        />
      </div>

      <span
        aria-hidden="true"
        class="pointer-events-none absolute right-3 bottom-12 -z-10 font-serif text-6xl font-bold italic text-primary-100"
      >
        {data.sid}-{sticker.pid}
      </span>

      <div class="text-sm text-default-600">
        <p class="truncate">{m().sticker.game}: {resolveMultilingual(sticker.game, locale.current)}</p>
        <p class="truncate">{m().sticker.lass}: {resolveMultilingual(sticker.loli, locale.current)}</p>
      </div>

      <div class="mt-1 flex items-center justify-between">
        <a
          href={localizedPath(locale.current, `/sticker/${data.sid}-${sticker.pid}`)}
          class="border border-primary px-3 py-1 text-sm text-primary transition hover:bg-primary hover:text-white"
        >
          {m().sticker.original}
        </a>
        <button
          type="button"
          aria-label={m().sticker.download}
          onclick={() =>
            downloadImage(`/kun-galgame-stickers/telegram/KUNgal${data.sid}/${sticker.pid}.png`)}
          class="flex h-9 w-9 items-center justify-center text-2xl text-primary transition hover:bg-content2 hover:text-primary-600"
        >
          <Icon icon="line-md:download-outline" />
        </button>
      </div>
    </article>
  {/each}
</div>

// apps/web/app/pages/sticker/[sid].vue
<script setup lang="ts">
const { t, locale } = useI18n()
const localePath = useLocalePath()
const route = useRoute()
const sid = computed(() => Number(route.params.sid))

const { data: pack } = await useAsyncData(
  () => `sticker-pack-${sid.value}`,
  () => fetchPack(sid.value)
)

if (!pack.value) {
  throw createError({ statusCode: 404, statusMessage: t('sticker.notFound') })
}

useSeoMeta({
  title: `${t('sticker.title')} [${sid.value}]`,
  description: t('sticker.description')
})

const downloadImage = async (path: string) => {
  const response = await fetch(path)
  const blob = await response.blob()
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = path.split('/').pop() ?? 'sticker.png'
  a.click()
  URL.revokeObjectURL(url)
}
</script>

<template>
  <div class="grid grid-cols-2 gap-5 sm:grid-cols-3 md:grid-cols-4">
    <KunCard
      v-for="sticker in pack?.stickers ?? []"
      :key="sticker.pid"
      color="default"
      class-name="relative flex flex-col gap-2 p-3"
    >
      <div class="aspect-square w-full overflow-hidden">
        <img
          :src="`/stickers/KUNgal${sid}/${sticker.pid}.webp`"
          alt=""
          width="320"
          height="320"
          loading="lazy"
          class="h-full w-full object-cover"
        >
      </div>
      <div class="text-default-600 text-sm">
        <p class="truncate">
          {{ t('sticker.game') }}: {{ resolveMultilingual(sticker.game, locale) }}
        </p>
        <p class="truncate">
          {{ t('sticker.lass') }}: {{ resolveMultilingual(sticker.loli, locale) }}
        </p>
      </div>
      <div class="mt-1 flex items-center justify-between">
        <KunButton
          size="sm"
          variant="bordered"
          :href="localePath(`/sticker/${sid}-${sticker.pid}`)"
        >
          {{ t('sticker.original') }}
        </KunButton>
        <KunButton
          is-icon-only
          variant="light"
          :aria-label="t('sticker.download')"
          @click="downloadImage(`/kun-galgame-stickers/telegram/KUNgal${sid}/${sticker.pid}.png`)"
        >
          <KunIcon name="lucide:download" class="text-xl" />
        </KunButton>
      </div>
    </KunCard>
  </div>
</template>
